# Generated by Django 3.0.2 on 2020-01-02 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teacher22',
        ),
    ]
